// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _02_first_mvc_app.Data;

#nullable disable

namespace _02_first_mvc_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_02_first_mvc_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2022, 12, 8, 13, 25, 40, 992, DateTimeKind.Local).AddTicks(9332),
                            Email = "saper@gmail.com",
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2022, 12, 8, 13, 25, 40, 992, DateTimeKind.Local).AddTicks(9374),
                            Email = "blabla@gmail.com",
                            Name = "Vlad"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2022, 12, 8, 13, 25, 40, 992, DateTimeKind.Local).AddTicks(9376),
                            Email = "mister@ukr.net",
                            Name = "John"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2022, 12, 8, 13, 25, 40, 992, DateTimeKind.Local).AddTicks(9379),
                            Email = "developer@gmail.com",
                            Name = "Lilia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
